export const devLogos = [
  { boot: "assets/logo/bootstrapL.png" },
  { css: "assets/logo/css3L.png" },
  { html: "assets/logo/html5L.png" },
  { javaS: "assets/logo/javascriptL.png" },
  { jquery: "assets/logo/jqueryL.png" },
  { mern: "assets/logo/mernL.png" },
  { sql: "assets/logo/mySQL.png" },
  { php: "assets/logo/phpL.png" },
  { react: "assets/logo/reactL.png" },
  { sass: "assets/logo/sass.png" },
  { mongo: "assets/logo/mongo.png" },
  { node: "assets/logo/node.png" },
  { express: "assets/logo/express.png" },
  { mhw: "assets/logo/mhwWhite.png" },
  { dir: "assets/logo/dir.png" },
  { specks: "assets/logo/specks2.png" },
];
